export type ExpansionPost = {
  title: string;
  slug: string;
  category: string;
  focusKeyword: string;
  excerpt: string;
  sourceUrl: string;
  body: string;
};

export type ExpansionJob = {
  title: string;
  company: string;
  description: string;
  location: string;
  category: string;
  applyUrl: string;
  isRemote: boolean;
};

const post = (
  title: string,
  slug: string,
  category: string,
  focusKeyword: string,
  excerpt: string,
  sourceUrl: string,
  body: string,
): ExpansionPost => ({ title, slug, category, focusKeyword, excerpt, sourceUrl, body });

const sourceBody = (summary: string, sourceUrl: string, checklist: string[]) =>
  `## Overview\n\n${summary}\n\n## What to check before applying\n\n${checklist.map(item => `- ${item}`).join('\n')}\n\n## Official source\n\nUse the official source for eligibility, dates, fees, syllabus, vacancies, or application status: [Open official source](${sourceUrl}). Blog-Ghar does not guarantee a deadline or vacancy; verify the page before taking action.`;

export const expansionPosts: ExpansionPost[] = [
  post('Worldwide Scholarship Search: A Practical Guide to Official Sources', 'worldwide-scholarship-search-official-sources', 'Worldwide Education', 'worldwide scholarships', 'How to find legitimate international scholarships without relying on unverified listings.', 'https://www.studyportals.com/scholarships/', sourceBody('International scholarships vary by country, institution, residency, and intake. Start with an official government or university page and treat aggregator results as discovery only.', 'https://www.studyportals.com/scholarships/', ['Confirm the awarding body and host institution.', 'Check nationality, language, and academic requirements.', 'Never pay a recruiter to submit a scholarship application.'])),
  post('UN Careers: How to Find and Apply for United Nations Opportunities', 'un-careers-how-to-apply', 'Worldwide Jobs', 'UN careers', 'A source-first guide to searching United Nations vacancies and internships.', 'https://careers.un.org/', sourceBody('The United Nations careers portal publishes vacancy notices, job networks, and application instructions for UN Secretariat opportunities.', 'https://careers.un.org/', ['Read the complete vacancy notice and closing time.', 'Create your profile on the official portal.', 'Match your experience to the listed requirements rather than copying generic keywords.'])),
  post('WHO Careers: Official Global Health Job Search Guide', 'who-careers-global-health-jobs', 'Worldwide Jobs', 'WHO careers', 'Where to verify World Health Organization vacancies, contracts, and application instructions.', 'https://www.who.int/careers', sourceBody('WHO publishes its careers information and vacancy links through its official website. Roles may have specific professional, language, and location requirements.', 'https://www.who.int/careers', ['Use only the who.int careers domain.', 'Check the contract type and duty station.', 'Do not send money or original identity documents to an unverified contact.'])),
  post('World Bank Careers: Application Steps and Candidate Checklist', 'world-bank-careers-application-guide', 'Worldwide Jobs', 'World Bank careers', 'A practical guide to the official World Bank Group careers portal.', 'https://www.worldbank.org/en/about/careers', sourceBody('World Bank Group careers include professional, analyst, and early-career pathways. Each vacancy states its own eligibility and application process.', 'https://www.worldbank.org/en/about/careers', ['Review the vacancy-specific education and experience criteria.', 'Prepare a concise CV with measurable work evidence.', 'Track applications through the official careers system.'])),
  post('Remote Work Across Countries: Legal and Tax Checks Before Accepting', 'international-remote-work-legal-checklist', 'Worldwide Careers', 'international remote work', 'A compliance checklist for candidates considering cross-border remote roles.', 'https://www.ilo.org/global/topics/employment-security/lang--en/index.htm', sourceBody('Remote work can involve employment, immigration, payroll, social-security, and data-protection rules in more than one jurisdiction. This is an information guide, not legal or tax advice.', 'https://www.ilo.org/global/topics/employment-security/lang--en/index.htm', ['Confirm which entity employs and pays you.', 'Ask where work may legally be performed.', 'Get tax and immigration advice for your situation.'])),
  post('IELTS, TOEFL, and PTE: Choosing an English Test by Official Rules', 'ielts-toefl-pte-official-comparison', 'Worldwide Education', 'IELTS TOEFL PTE comparison', 'Compare official test providers and verify score requirements before booking.', 'https://www.ielts.org/', sourceBody('IELTS, TOEFL, and PTE have different test formats, score reports, and institution policies. Always check the receiving university or immigration authority first.', 'https://www.ielts.org/', ['Check the institution’s accepted-test list.', 'Read the current identification and rescheduling rules.', 'Book through the provider’s official website or an authorised centre.'])),
  post('How to Verify an International Job Offer and Avoid Recruitment Scams', 'verify-international-job-offer', 'Worldwide Jobs', 'verify overseas job offer', 'A safety-first checklist for validating overseas recruitment messages.', 'https://www.interpol.int/en/Crimes/Financial-crime/Online-scams', sourceBody('Real employers do not need a candidate to pay for a guaranteed job, fake visa, or “processing release”. Verify the employer independently before sharing sensitive information.', 'https://www.interpol.int/en/Crimes/Financial-crime/Online-scams', ['Open the employer website independently, not only from an email.', 'Check that the vacancy exists on the employer’s official domain.', 'Do not pay for a job offer or share one-time passwords.'])),
  post('India UPSC CMS Exam: Eligibility, Official Notice, and Preparation Plan', 'upsc-cms-exam-official-guide', 'India Exams', 'UPSC CMS exam', 'A source-linked overview of the Combined Medical Services Examination and how to verify its notice.', 'https://upsc.gov.in/examinations/active-exams', sourceBody('UPSC CMS is conducted by the Union Public Service Commission for eligible medical graduates. Dates, vacancies, and rules can change, so use the active examinations page and the notice issued for the relevant cycle.', 'https://upsc.gov.in/examinations/active-exams', ['Read the official notice for the cycle you are targeting.', 'Confirm internship and medical qualification rules.', 'Use the official syllabus and previous papers to plan revision.'])),
  post('UPSC Civil Services Exam: Official Syllabus and Application Workflow', 'upsc-cse-official-syllabus-application', 'India Exams', 'UPSC CSE syllabus', 'A practical, official-source guide to Civil Services Examination stages.', 'https://upsc.gov.in/examinations/active-exams', sourceBody('UPSC Civil Services Examination has notification, preliminary, main, and personality-test stages described in the official notice.', 'https://upsc.gov.in/examinations/active-exams', ['Download the current notification from upsc.gov.in.', 'Record the application closing date in your calendar.', 'Use the official syllabus as the boundary for preparation.'])),
  post('India SSC CGL: Official Notification, Syllabus, and Preparation Checklist', 'ssc-cgl-official-notification-guide', 'India Exams', 'SSC CGL exam', 'How to use the Staff Selection Commission portal for CGL information.', 'https://ssc.gov.in/', sourceBody('SSC CGL recruitment details, calendar updates, notices, and application links are published by the Staff Selection Commission.', 'https://ssc.gov.in/', ['Use the current notice, not an old coaching summary.', 'Check age limits and post-wise qualifications.', 'Save your registration number and submitted application copy.'])),
  post('NEET UG: Official NTA Information and Counselling Verification Guide', 'neet-ug-official-nta-guide', 'India Exams', 'NEET UG official website', 'Find authentic NEET UG notices, information bulletins, and counselling links.', 'https://exams.nta.ac.in/NEET/', sourceBody('The National Testing Agency publishes NEET UG examination information through its official exam portal. Counselling may be handled by designated authorities described in official notices.', 'https://exams.nta.ac.in/NEET/', ['Download the information bulletin for your year.', 'Verify correction-window and admit-card announcements.', 'Follow the counselling authority named in the official notice.'])),
  post('JEE Main: Official NTA Exam Pattern and Registration Checklist', 'jee-main-official-registration-guide', 'India Exams', 'JEE Main official registration', 'A no-rumour checklist for JEE Main application and exam updates.', 'https://jeemain.nta.nic.in/', sourceBody('JEE Main sessions, application notices, city intimation, and results are published through the official NTA portal.', 'https://jeemain.nta.nic.in/', ['Check session-specific dates and fee rules.', 'Review the official information bulletin.', 'Use the candidate login only on the official domain.'])),
  post('IBPS PO and Clerk: Official Recruitment Calendar and Application Guide', 'ibps-po-clerk-official-guide', 'India Exams', 'IBPS PO exam', 'How to verify IBPS banking recruitment notices and prepare from the official pattern.', 'https://www.ibps.in/', sourceBody('IBPS publishes recruitment notifications, calendars, and information for participating public-sector bank examinations.', 'https://www.ibps.in/', ['Read the notification for participating banks and eligibility.', 'Check the official exam pattern and language options.', 'Apply only through the link provided on ibps.in.'])),
  post('RBI Grade B: Official Recruitment Notice and Phase-Wise Study Plan', 'rbi-grade-b-official-guide', 'India Exams', 'RBI Grade B exam', 'Use RBI’s own recruitment notices to plan Grade B preparation.', 'https://opportunities.rbi.org.in/', sourceBody('RBI publishes Grade B recruitment information, vacancies, and instructions through its opportunities portal.', 'https://opportunities.rbi.org.in/', ['Confirm the stream and qualification requirements.', 'Read the phase-wise syllabus in the current notice.', 'Watch for corrigenda and changes on the official portal.'])),
  post('GATE: Official IIT Examination Portal, Papers, and Score Validity', 'gate-exam-official-portal-guide', 'India Exams', 'GATE official website', 'A source-first GATE guide for candidates comparing papers and score information.', 'https://gate2026.iitg.ac.in/', sourceBody('GATE is administered by the IITs and IISc through the organising institute’s official portal for each cycle.', 'https://gate2026.iitg.ac.in/', ['Use the year-specific organising institute website.', 'Download the syllabus for the paper you select.', 'Check score and admission rules with the institution or recruiter.'])),
  post('CTET: Official CBSE Bulletin, Eligibility, and Application Steps', 'ctet-official-cbse-guide', 'India Exams', 'CTET official notification', 'Where to find authentic CTET notices and eligibility information.', 'https://ctet.nic.in/', sourceBody('CBSE publishes CTET bulletins, application notices, answer keys, and results on the official CTET portal.', 'https://ctet.nic.in/', ['Read the bulletin for Paper I or Paper II eligibility.', 'Check the correction and document rules.', 'Use only ctet.nic.in for candidate services.'])),
  post('India Job Search: Government Portals to Check Before Applying', 'india-government-job-portals-official', 'India Jobs', 'India government jobs official portals', 'A curated list of official Indian recruitment portals for safer job discovery.', 'https://www.ncs.gov.in/', sourceBody('India’s National Career Service, UPSC, SSC, and public-sector organisations publish vacancies on their own portals. A listing is not an endorsement and availability changes frequently.', 'https://www.ncs.gov.in/', ['Verify the employer and advertisement number.', 'Read application fees and closing dates in the notice.', 'Never pay an intermediary for a guaranteed government job.'])),
  post('USA Federal Jobs: How to Search and Apply on USAJOBS', 'usajobs-federal-application-guide', 'USA Exams & Jobs', 'USAJOBS application', 'A practical guide to federal vacancy searches and applications on the official portal.', 'https://www.usajobs.gov/', sourceBody('USAJOBS is the U.S. federal government’s central employment website. Each announcement contains its own qualifications and instructions.', 'https://www.usajobs.gov/', ['Read the “How to Apply” section completely.', 'Check citizenship, security, and location requirements.', 'Submit before the announcement closes or reaches its applicant limit.'])),
  post('USA Civil Service Exams and Hiring: What Applicants Should Verify', 'usa-civil-service-exams-hiring-guide', 'USA Exams & Jobs', 'USA civil service jobs', 'Understand how U.S. government hiring differs by agency and announcement.', 'https://www.opm.gov/policy-data-oversight/hiring-information/', sourceBody('U.S. federal hiring rules and assessment methods depend on the agency and role. The Office of Personnel Management provides official hiring information.', 'https://www.opm.gov/policy-data-oversight/hiring-information/', ['Follow the exact announcement requirements.', 'Do not assume every federal role uses one universal exam.', 'Use agency-specific instructions where provided.'])),
  post('SAT and ACT: Official College Admission Test Planning Guide', 'usa-sat-act-official-planning-guide', 'USA Exams & Jobs', 'SAT official registration', 'How to compare official U.S. college admission testing information.', 'https://satsuite.collegeboard.org/sat', sourceBody('The College Board publishes SAT dates, registration, policies, and score information. Colleges set their own testing policies.', 'https://satsuite.collegeboard.org/sat', ['Check each college’s current testing policy.', 'Confirm registration deadlines and identification rules.', 'Use official practice material to learn the format.'])),
  post('GRE and TOEFL: Official ETS Registration and Score Reporting Basics', 'ets-gre-toefl-official-guide', 'USA Exams & Jobs', 'GRE TOEFL official', 'A source-first guide to ETS tests used by universities and institutions worldwide.', 'https://www.ets.org/', sourceBody('ETS provides official information for GRE and TOEFL registration, scores, and test-day policies. Requirements vary by institution.', 'https://www.ets.org/', ['Check the receiving programme’s required test and score.', 'Read current rescheduling and ID rules.', 'Send scores only to institutions you have verified.'])),
  post('UK Civil Service Jobs: Official Application and Assessment Guide', 'uk-civil-service-jobs-guide', 'UK Exams & Jobs', 'UK Civil Service Jobs', 'Find UK government roles and understand the official application flow.', 'https://www.civilservicejobs.service.gov.uk/', sourceBody('The UK Civil Service Jobs portal lists government vacancies and describes role-specific recruitment stages.', 'https://www.civilservicejobs.service.gov.uk/', ['Read the success profiles and behaviours requested.', 'Check nationality and right-to-work requirements.', 'Keep a copy of submitted evidence and deadlines.'])),
  post('UCAS Applications: UK University Deadlines and Verification Checklist', 'ucas-application-official-guide', 'UK Exams & Jobs', 'UCAS application', 'A safe workflow for UK university applications using the official admissions service.', 'https://www.ucas.com/undergraduate/applying-university', sourceBody('UCAS manages applications for many UK undergraduate courses. Course providers set requirements and may have different deadlines.', 'https://www.ucas.com/undergraduate/applying-university', ['Check course-specific entry requirements.', 'Record the deadline shown for your application type.', 'Use the university website for fee and visa details.'])),
  post('NHS Jobs: How to Search Legitimate UK Healthcare Vacancies', 'nhs-jobs-official-search-guide', 'UK Exams & Jobs', 'NHS Jobs UK', 'Use the NHS Jobs portal to find and verify healthcare vacancies.', 'https://www.jobs.nhs.uk/', sourceBody('NHS Jobs is the official recruitment service for many NHS roles. Individual employers specify registration, experience, and right-to-work requirements.', 'https://www.jobs.nhs.uk/', ['Check the employing trust and job reference.', 'Review professional registration requirements.', 'Apply through the vacancy page, not an unsolicited payment request.'])),
  post('Germany Jobs: Official Bundesagentur für Arbeit Search Guide', 'germany-arbeitsagentur-job-search', 'Germany Exams & Jobs', 'Germany official jobs', 'How international applicants can start with Germany’s federal employment service.', 'https://www.arbeitsagentur.de/jobsuche/', sourceBody('The Bundesagentur für Arbeit provides Germany’s official job search service. German language, recognition, and work-authorisation requirements vary by role.', 'https://www.arbeitsagentur.de/jobsuche/', ['Check the original German vacancy text.', 'Verify qualification recognition where required.', 'Confirm visa and work permission through official government guidance.'])),
  post('Germany Study and Scholarships: DAAD Official Search Workflow', 'germany-daad-scholarship-guide', 'Germany Exams & Jobs', 'DAAD scholarships', 'A practical guide to searching scholarships and study information through DAAD.', 'https://www.daad.de/en/studying-in-germany/scholarships/', sourceBody('DAAD provides scholarship and study information for international students. Each programme has its own eligibility, documents, and deadline.', 'https://www.daad.de/en/studying-in-germany/scholarships/', ['Open the programme’s full call for applications.', 'Check whether the award is university-specific.', 'Use the university’s official page for admission requirements.'])),
  post('Germany German-Language Exams: Goethe and TestDaF Official Resources', 'germany-german-language-exams-guide', 'Germany Exams & Jobs', 'German language exam', 'Compare official preparation and registration sources for German-language certification.', 'https://www.goethe.de/en/spr/kup/prf.html', sourceBody('Goethe-Institut and TestDaF publish official exam formats, dates, and registration information. Immigration and university requirements differ.', 'https://www.goethe.de/en/spr/kup/prf.html', ['Confirm the certificate accepted by your target institution.', 'Read exam-level and module requirements.', 'Register with an authorised test centre.'])),
  post('Canada Government Jobs: Official GC Jobs Application Guide', 'canada-gc-jobs-application-guide', 'Canada Exams & Jobs', 'GC Jobs Canada', 'How to search and apply for Canadian federal public-service positions.', 'https://www.canada.ca/en/services/jobs/opportunities/government.html', sourceBody('The Government of Canada publishes federal opportunities and hiring information through Canada.ca and the GC Jobs system.', 'https://www.canada.ca/en/services/jobs/opportunities/government.html', ['Read language, education, and security requirements.', 'Answer screening questions using evidence from your experience.', 'Save the reference number and submitted application.'])),
  post('Canada Job Bank: Verified Job Search and Work-Permit Awareness', 'canada-job-bank-official-guide', 'Canada Exams & Jobs', 'Canada Job Bank', 'Use Canada’s official Job Bank while checking work authorisation separately.', 'https://www.jobbank.gc.ca/', sourceBody('Job Bank is Canada’s national employment service. A job listing does not itself grant permission to work in Canada.', 'https://www.jobbank.gc.ca/', ['Confirm whether the employer is recruiting internationally.', 'Check immigration rules on Canada.ca.', 'Verify the employer and never pay for a job offer.'])),
  post('Canada Express Entry: Official Immigration Profile Checklist', 'canada-express-entry-official-guide', 'Canada Exams & Jobs', 'Canada Express Entry', 'A source-first overview of Express Entry information and document planning.', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html', sourceBody('Express Entry is an immigration application system with eligibility and document rules published by Immigration, Refugees and Citizenship Canada.', 'https://www.canada.ca/en/immigration-refugees-citizenship/services/immigrate-canada/express-entry.html', ['Use the official eligibility questionnaire.', 'Keep language-test and education documents current.', 'Treat consultant claims as unverified until confirmed on Canada.ca.'])),
  post('Australia APS Jobs: Official Public-Service Recruitment Guide', 'australia-aps-jobs-official-guide', 'Australia Exams & Jobs', 'APS Jobs Australia', 'How to search Australian Government vacancies on the official APS portal.', 'https://www.apsjobs.gov.au/', sourceBody('APS Jobs lists Australian Public Service opportunities and role-specific selection requirements.', 'https://www.apsjobs.gov.au/', ['Read the position description and citizenship rules.', 'Prepare examples using the requested capabilities.', 'Submit through the official vacancy workflow.'])),
  post('Australia Skills Assessment and Skilled Migration: Official Sources', 'australia-skilled-migration-official-sources', 'Australia Exams & Jobs', 'Australia skilled migration', 'Where to verify skills, occupation, and visa requirements for Australia.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing', sourceBody('Australian visa and skilled migration requirements are published by the Department of Home Affairs and relevant assessing authorities.', 'https://immi.homeaffairs.gov.au/visas/getting-a-visa/visa-listing', ['Check the exact visa subclass.', 'Identify the correct skills-assessing authority.', 'Use current government rules rather than old social-media timelines.'])),
  post('Japan JASSO Scholarships: Official International Student Guide', 'japan-jasso-scholarship-guide', 'Japan Exams & Jobs', 'JASSO scholarships', 'How international students can verify Japanese scholarship and study information.', 'https://www.jasso.go.jp/en/', sourceBody('JASSO provides official information for international students, scholarships, and study support in Japan.', 'https://www.jasso.go.jp/en/', ['Check whether applications go through your institution.', 'Confirm language and academic requirements.', 'Use the university’s official admissions page for final requirements.'])),
  post('Singapore Public-Service Careers: Official Jobs and Scholarship Sources', 'singapore-public-service-careers-guide', 'Asia Exams & Jobs', 'Singapore government jobs', 'A source-linked starting point for Singapore public-service careers and scholarships.', 'https://www.careers.gov.sg/', sourceBody('Singapore’s Careers@Gov portal publishes public-service opportunities and explains application requirements.', 'https://www.careers.gov.sg/', ['Check citizenship and service obligations.', 'Read the full role description.', 'Use official agency pages for follow-up requirements.'])),
  post('EU Careers: EPSO Competition and Application Basics', 'eu-epsο-careers-official-guide'.replace('ο', 'o'), 'Europe Exams & Jobs', 'EPSO careers', 'Understand the official starting point for European Union institution competitions.', 'https://eu-careers.europa.eu/en', sourceBody('EU Careers publishes information about opportunities and competitions for EU institutions and bodies.', 'https://eu-careers.europa.eu/en', ['Check nationality and language requirements.', 'Read the competition notice and testing stages.', 'Use the candidate account on the official portal.'])),
  post('International Development Jobs: UNDP Official Vacancy Search', 'undp-careers-official-guide', 'Worldwide Jobs', 'UNDP careers', 'A practical guide to finding UNDP roles and verifying vacancy details.', 'https://www.undp.org/careers', sourceBody('UNDP publishes job opportunities and hiring information through its official careers page.', 'https://www.undp.org/careers', ['Verify the hiring unit and contract type.', 'Follow the vacancy-specific application instructions.', 'Be cautious of messages asking for payment or bank details.'])),
  post('Public-Health Careers Worldwide: UNICEF Official Application Guide', 'unicef-careers-official-guide', 'Worldwide Jobs', 'UNICEF careers', 'How to use UNICEF’s official careers portal for international opportunities.', 'https://www.unicef.org/careers', sourceBody('UNICEF lists professional, consultancy, internship, and other opportunities through its official careers information.', 'https://www.unicef.org/careers', ['Check the position’s duty station and contract category.', 'Prepare evidence for the listed competencies.', 'Apply through the official UNICEF system.'])),
  post('ILO Jobs and Internships: Official Vacancy Verification Checklist', 'ilo-careers-official-guide', 'Worldwide Jobs', 'ILO careers', 'Find official International Labour Organization opportunities and avoid fake recruiters.', 'https://jobs.ilo.org/', sourceBody('The ILO careers portal publishes vacancies and application instructions for roles at the organisation.', 'https://jobs.ilo.org/', ['Check the vacancy reference and closing date.', 'Use the official applicant account.', 'Ignore requests for payment, gift cards, or visa fees from individuals.'])),
  post('International Civil-Service Exam Preparation: A Transferable Study System', 'international-civil-service-exam-study-system', 'Worldwide Education', 'international civil service exam preparation', 'A reusable preparation framework for official public-service competitions across countries.', 'https://careers.un.org/jobopenings', sourceBody('Public-service selection differs by institution, but candidates can build a reliable system around the official notice, syllabus, practice, and evidence-based applications.', 'https://careers.un.org/jobopenings', ['Start with the official competency framework.', 'Use timed practice and review errors.', 'Track each country’s eligibility and document rules separately.'])),
  post('How to Build a Country-Wise Exam Calendar Without Missing Deadlines', 'country-wise-exam-calendar-method', 'Worldwide Education', 'country wise exam calendar', 'A structured method for tracking exam notices across India, the USA, Europe, and other countries.', 'https://www.gov.uk/get-information-about-your-application', sourceBody('Exam calendars change. A country-wise tracker should link directly to the authority, record the notice date, and show the last verified time.', 'https://www.gov.uk/get-information-about-your-application', ['Store the official notice URL, not only a screenshot.', 'Record timezone and closing time.', 'Recheck dates after corrigenda or portal updates.'])),
  post('Job Application SEO Guide: What Candidates Should Actually Search For', 'job-search-keywords-by-country', 'Worldwide Careers', 'job search keywords by country', 'A transparent keyword strategy for discovering official jobs without implying that a vacancy is open.', 'https://www.linkedin.com/jobs/', sourceBody('Search terms differ by country: title, city, work authorisation, language, and contract type all affect results. Search results are not proof of an open role.', 'https://www.linkedin.com/jobs/', ['Use the employer’s official site to verify a listing.', 'Add the country’s local job title and language.', 'Check posting date and closing instructions.'])),
  post('International CV and Resume Standards: Country-Specific Checks', 'international-cv-resume-country-guide', 'Worldwide Careers', 'international CV format', 'A practical comparison checklist for CV expectations across regions.', 'https://europa.eu/europass/en/create-europass-cv', sourceBody('CV conventions vary. Europass provides one official European format, while employers elsewhere may request different structures. Always follow the vacancy instructions.', 'https://europa.eu/europass/en/create-europass-cv', ['Follow the employer’s requested file format.', 'Remove unsupported claims and unverifiable certificates.', 'Keep personal data limited to what the employer needs.'])),
  post('Worldwide Fellowship Applications: How to Check Eligibility and Funding', 'worldwide-fellowship-application-checklist', 'Worldwide Education', 'international fellowships', 'A source-first checklist for fellowships offered by universities, foundations, and public bodies.', 'https://www.fulbrightprogram.org/', sourceBody('Fellowship terms differ widely. A credible programme states its sponsor, eligibility, funding terms, timeline, and application channel.', 'https://www.fulbrightprogram.org/', ['Confirm the sponsor and host institution.', 'Read what the funding covers and excludes.', 'Use the programme’s official contact details for questions.'])),
  post('Government Exam and Job Scam Red Flags: A Global Safety Guide', 'government-exam-job-scam-red-flags', 'Worldwide Jobs', 'government job scam warning', 'Recognise fake notices, impersonation, and payment requests before applying.', 'https://www.consumer.ftc.gov/articles/job-scams', sourceBody('Fraudsters often impersonate agencies, use copied logos, and demand payment or personal information. Official portals publish their own application paths.', 'https://www.consumer.ftc.gov/articles/job-scams', ['Check the domain character by character.', 'Search the agency site for the same notice.', 'Report suspicious messages and do not send money.'])),
  post('France Jobs: Official Public-Service and Employment Sources', 'france-official-jobs-guide', 'Europe Exams & Jobs', 'France official jobs', 'Where to verify French public-sector and employment opportunities.', 'https://choisirleservicepublic.gouv.fr/', sourceBody('French public-service vacancies are published through official government services. Requirements, language, and residency rules depend on the role.', 'https://choisirleservicepublic.gouv.fr/', ['Read the vacancy in its original language.', 'Check nationality and qualification rules.', 'Use the official application account and reference number.'])),
  post('Spain Public Employment: Official Search and Exam Notice Guide', 'spain-public-employment-exams-guide', 'Europe Exams & Jobs', 'Spain public employment exams', 'A source-first guide to Spanish public employment notices and competitions.', 'https://administracion.gob.es/pagFront/empleoBecas/empleo/buscaEmpleo.htm', sourceBody('Spain publishes public employment information and calls through official administration services. Each call defines its own eligibility and dates.', 'https://administracion.gob.es/pagFront/empleoBecas/empleo/buscaEmpleo.htm', ['Check the exact convocatoria and publication date.', 'Confirm language and qualification requirements.', 'Follow the authority named in the official call.'])),
  post('New Zealand Government Jobs: Official Careers and Application Checklist', 'new-zealand-government-jobs-guide', 'Oceania Exams & Jobs', 'New Zealand government jobs', 'How to find and verify New Zealand public-sector vacancies.', 'https://jobs.govt.nz/', sourceBody('New Zealand government roles are listed on the official jobs.govt.nz portal and on agency career pages.', 'https://jobs.govt.nz/', ['Check work rights and location requirements.', 'Use the role’s closing date and reference.', 'Submit through the official employer or government portal.'])),
  post('South Africa Government Jobs: DPSA Vacancy Verification Guide', 'south-africa-dpsa-vacancies-guide', 'Africa Exams & Jobs', 'South Africa government jobs', 'A practical way to verify South African public-service vacancy notices.', 'https://www.dpsa.gov.za/newsroom/psv/', sourceBody('The Department of Public Service and Administration publishes public-service vacancy information and related notices through official channels.', 'https://www.dpsa.gov.za/newsroom/psv/', ['Match the post title and reference to the official notice.', 'Check the required form and submission address.', 'Ignore recruiters asking for payment.'])),
  post('South Korea Study and Scholarship Sources: Official NIIED Guide', 'south-korea-niied-scholarship-guide', 'Asia Exams & Jobs', 'South Korea scholarships', 'How to start with official Korean government scholarship information.', 'https://www.studyinkorea.go.kr/en/main.do', sourceBody('The Korean government’s Study in Korea service provides official study and scholarship information for international students.', 'https://www.studyinkorea.go.kr/en/main.do', ['Confirm the programme’s application route.', 'Check language and document requirements.', 'Verify deadlines with the university or official programme notice.'])),
];

export const expansionPostsWithInternship: ExpansionPost = post('Global Internship Search: How to Verify Official Programme Pages', 'global-internship-official-search-guide', 'Worldwide Careers', 'international internships', 'A verification workflow for finding legitimate internships from universities, governments, and international organisations.', 'https://careers.un.org/jobopenings', sourceBody('Internship eligibility, location, duration, and compensation vary by programme. Start at the sponsoring organisation’s official opportunities page and confirm the exact notice.', 'https://careers.un.org/jobopenings', ['Confirm the sponsor and host organisation.', 'Check whether the programme is paid, unpaid, or funded.', 'Apply only through the official application system.']));

expansionPosts.push(expansionPostsWithInternship);

export const expansionJobs: ExpansionJob[] = [
  { title: 'Federal Government Opportunities', company: 'USAJOBS', description: 'Search current U.S. federal vacancies and apply through the official announcement.', location: 'United States', category: 'Government & Public Service', applyUrl: 'https://www.usajobs.gov/', isRemote: false },
  { title: 'United Nations Vacancies', company: 'United Nations', description: 'Browse official UN Secretariat vacancies, internships, and job networks.', location: 'Worldwide', category: 'International Organisations', applyUrl: 'https://careers.un.org/', isRemote: false },
  { title: 'World Health Organization Opportunities', company: 'World Health Organization', description: 'Review current WHO career opportunities and vacancy instructions.', location: 'Worldwide', category: 'Healthcare', applyUrl: 'https://www.who.int/careers', isRemote: false },
  { title: 'World Bank Group Careers', company: 'World Bank Group', description: 'Find official World Bank Group roles and early-career programmes.', location: 'Worldwide', category: 'International Organisations', applyUrl: 'https://www.worldbank.org/en/about/careers', isRemote: false },
  { title: 'India Government Job Search', company: 'National Career Service', description: 'Search vacancies and career services on India’s official National Career Service.', location: 'India', category: 'Government & Public Service', applyUrl: 'https://www.ncs.gov.in/', isRemote: false },
  { title: 'UK Civil Service Vacancies', company: 'UK Civil Service', description: 'Apply to UK government roles through the official Civil Service Jobs portal.', location: 'United Kingdom', category: 'Government & Public Service', applyUrl: 'https://www.civilservicejobs.service.gov.uk/', isRemote: false },
  { title: 'NHS Healthcare Vacancies', company: 'NHS Jobs', description: 'Search NHS vacancies and follow the employing organisation’s instructions.', location: 'United Kingdom', category: 'Healthcare', applyUrl: 'https://www.jobs.nhs.uk/', isRemote: false },
  { title: 'German Federal Job Search', company: 'Bundesagentur für Arbeit', description: 'Search Germany’s federal employment-service listings.', location: 'Germany', category: 'Government & Public Service', applyUrl: 'https://www.arbeitsagentur.de/jobsuche/', isRemote: false },
  { title: 'Canadian Federal Public-Service Jobs', company: 'Government of Canada', description: 'Find Canadian federal opportunities through the official government portal.', location: 'Canada', category: 'Government & Public Service', applyUrl: 'https://www.canada.ca/en/services/jobs/opportunities/government.html', isRemote: false },
  { title: 'Canada Job Bank Listings', company: 'Job Bank Canada', description: 'Search Canada’s national employment service and verify work authorisation separately.', location: 'Canada', category: 'General Careers', applyUrl: 'https://www.jobbank.gc.ca/', isRemote: false },
  { title: 'Australian Public Service Roles', company: 'APS Jobs', description: 'Browse Australian Government vacancies and position descriptions.', location: 'Australia', category: 'Government & Public Service', applyUrl: 'https://www.apsjobs.gov.au/', isRemote: false },
  { title: 'UNICEF Career Opportunities', company: 'UNICEF', description: 'Review UNICEF vacancies and application requirements on its official careers site.', location: 'Worldwide', category: 'International Organisations', applyUrl: 'https://www.unicef.org/careers', isRemote: false },
  { title: 'UNDP Career Opportunities', company: 'UNDP', description: 'Search official UNDP roles, consultancies, and programme opportunities.', location: 'Worldwide', category: 'International Organisations', applyUrl: 'https://www.undp.org/careers', isRemote: false },
  { title: 'ILO Vacancies', company: 'International Labour Organization', description: 'Browse official ILO vacancies and apply through the ILO jobs portal.', location: 'Worldwide', category: 'International Organisations', applyUrl: 'https://jobs.ilo.org/', isRemote: false },
  { title: 'Singapore Public-Service Careers', company: 'Careers@Gov', description: 'Search Singapore public-service opportunities on the official portal.', location: 'Singapore', category: 'Government & Public Service', applyUrl: 'https://www.careers.gov.sg/', isRemote: false },
];

export const additionalOfficialJobs: ExpansionJob[] = [
  ['FAO', 'https://jobs.fao.org/careersection/fao_external/jobsearch.ftl?lang=en', 'Worldwide'],
  ['WFP', 'https://www.wfp.org/careers', 'Worldwide'], ['UNHCR', 'https://www.unhcr.org/careers-us', 'Worldwide'],
  ['UNDP', 'https://www.undp.org/careers', 'Worldwide'], ['UNICEF', 'https://jobs.unicef.org/', 'Worldwide'],
  ['ILO', 'https://jobs.ilo.org/', 'Worldwide'], ['OECD', 'https://oecd.org/careers/', 'Worldwide'],
  ['WTO', 'https://www.wto.org/english/thewto_e/vacan_e/vacan_e.htm', 'Worldwide'],
  ['ADB', 'https://www.adb.org/work-with-us/careers', 'Asia-Pacific'], ['African Development Bank', 'https://www.afdb.org/en/about-us/careers', 'Africa'],
  ['EBRD', 'https://www.ebrd.com/careers.html', 'Europe'], ['NATO', 'https://www.nato.int/cps/en/natolive/recruitment.htm', 'Worldwide'],
  ['INTERPOL', 'https://www.interpol.int/Who-we-are/Careers', 'Worldwide'], ['Europol', 'https://www.europol.europa.eu/careers-procurement', 'Europe'],
  ['CERN', 'https://careers.cern/', 'Switzerland'], ['ESA', 'https://www.esa.int/About_Us/Careers_at_ESA', 'Europe'],
  ['NASA', 'https://www.nasa.gov/careers/', 'United States'], ['NOAA', 'https://www.noaa.gov/work-with-us', 'United States'],
  ['NIH', 'https://jobs.nih.gov/', 'United States'], ['CDC', 'https://jobs.cdc.gov/', 'United States'],
  ['FBI', 'https://www.fbijobs.gov/', 'United States'], ['CIA', 'https://www.cia.gov/careers/', 'United States'],
  ['U.S. Department of State', 'https://careers.state.gov/', 'United States'], ['UK Parliament', 'https://www.parliament.uk/about/careers/', 'United Kingdom'],
  ['Public Appointments UK', 'https://publicappointments.cabinetoffice.gov.uk/', 'United Kingdom'],
  ['Ireland Public Jobs', 'https://www.publicjobs.ie/', 'Ireland'], ['Netherlands Government', 'https://www.werkenbijdeoverheid.nl/', 'Netherlands'],
  ['Sweden Government Jobs', 'https://www.arbetsgivarverket.se/other-languages/english/working-in-the-government-sector/', 'Sweden'],
  ['Norway Government Jobs', 'https://www.jobbnorge.no/search/en', 'Norway'], ['Finland Valtiolle', 'https://www.valtiolle.fi/en-US', 'Finland'],
  ['Denmark Jobnet', 'https://job.jobnet.dk/CV/FindWork', 'Denmark'], ['Austria Public Service', 'https://www.bundeskanzleramt.gv.at/en/the-federal-chancellery/careers.html', 'Austria'],
  ['Switzerland Confederation', 'https://www.stelle.admin.ch/stelle/en/home.html', 'Switzerland'],
  ['Brazil Government', 'https://www.gov.br/servidor/pt-br', 'Brazil'], ['Chile Public Employment', 'https://www.empleospublicos.cl/', 'Chile'],
].map(([company, applyUrl, location]) => ({
  title: `${company} official vacancy search`,
  company,
  description: `Search current vacancies and follow the employer's official application instructions. Availability changes frequently.`,
  location,
  category: 'Official Vacancy Portals',
  applyUrl,
  isRemote: false,
}));
