import type { ExpansionPost } from './expanded-content';

type ResearchSeed = {
  title: string;
  slug: string;
  category: string;
  focusKeyword: string;
  excerpt: string;
  sourceUrl: string;
  answer: string;
  steps: string[];
  documents: string[];
  mistakes: string[];
  caveat: string;
};

const body = (p: ResearchSeed) => `## Direct answer

${p.answer}

This guide is designed for applicants who need to complete the process themselves. The responsible authority, university, employer, or examination body remains the final decision-maker. Start from the source linked below, record the page title and the date you checked it, and use the same spelling of your name on every form.

## Step-by-step workflow

${p.steps.map((s, i) => `${i + 1}. ${s}`).join('\n')}

Do not treat a search-result snippet, consultant message, social-media post, or an old PDF as the current rule. Open the notice or service page, follow links inside that page, and save the reference number generated after submission. If a portal times out, take a screenshot of the error and contact the authority through the contact method printed on its own website rather than paying an intermediary.

## Documents and preparation checklist

${p.documents.map(d => `- ${d}`).join('\n')}

Scan documents in colour, keep readable file names, and retain the originals. Where a translation, legalisation, apostille, certified copy, language test, or professional registration is required, confirm who is allowed to certify it and whether the document must be recent. Never upload a passport or bank statement to a domain that is not the official authority or the institution named in the notice.

## Common mistakes and practical fixes

${p.mistakes.map(m => `- **Mistake:** ${m}`).join('\n')}

If your circumstances are unusual—dual nationality, a name change, an interrupted qualification, a previous refusal, an expired document, or a disability requiring an adjustment—ask the authority in writing before submitting. Keep both the question and the reply with your application evidence. A paid adviser cannot override a statutory rule or guarantee an outcome.

## Caveat for changing rules

${p.caveat}

## Official source

Use the primary source for the live form, eligibility, deadline, fee, appointment availability, syllabus, and appeal route: [Open the official source](${p.sourceUrl}). Blog-Ghar is an informational guide, not a government, university, immigration, or licensing service.`;

const researchSeedsEuropeAfrica: ResearchSeed[] = [
  {
    title: 'EU Diploma Recognition: How to Request a Statement of Comparability',
    slug: 'eu-diploma-recognition-statement-of-comparability',
    category: 'Europe Education',
    focusKeyword: 'EU diploma recognition',
    excerpt: 'A practical route for checking which national ENIC-NARIC body handles recognition of an overseas qualification.',
    sourceUrl: 'https://europa.eu/youreurope/citizens/education/recognition-of-qualifications/index_en.htm',
    answer: 'There is no single EU-wide diploma office. The correct route depends on the country, the profession, and whether you need academic admission or access to a regulated job. Your Europe explains the distinction and points applicants to the responsible national authority.',
    steps: ['Identify the destination country and whether the job is regulated.', 'Read that country’s ENIC-NARIC or competent-authority instructions.', 'Submit the requested diploma, transcript, identity evidence, and translations through the stated channel.', 'Use the resulting statement only for the purpose described and send it to the university or employer.'],
    documents: ['Final award certificate and complete transcript.', 'Identity document and evidence of name changes.', 'Certified translation only if the authority requires it.', 'Course descriptions when the authority asks for them.'],
    mistakes: ['Buying an “EU equivalency certificate” from an unofficial website.', 'Assuming recognition for university admission also grants a professional licence.', 'Sending incomplete transcripts and then missing a correction deadline.'],
    caveat: 'National procedures, fees, processing times, and document formats differ and can change. A regulated profession may require a separate language, registration, or aptitude step.',
  },
  {
    title: 'Erasmus Mundus Joint Masters: Finding the Official Catalogue and Applying',
    slug: 'erasmus-mundus-joint-masters-official-application',
    category: 'Europe Scholarships',
    focusKeyword: 'Erasmus Mundus scholarship application',
    excerpt: 'How applicants in Africa, Europe, and elsewhere can verify a joint master programme and apply to its consortium.',
    sourceUrl: 'https://education.ec.europa.eu/study-in-europe/programmes-and-scholarships/erasmus-mundus-joint-masters',
    answer: 'Erasmus Mundus Joint Masters are run by programme consortia, so each master’s own website publishes its entry requirements and application window. The EU page is the safe starting point for identifying genuine programmes and understanding the scholarship concept.',
    steps: ['Search the EU catalogue and shortlist programmes matching your degree and language ability.', 'Open the consortium website and read its current call, selection criteria, and required format.', 'Prepare the application before the consortium deadline, not a date copied from another programme.', 'Submit through the programme’s stated portal and save the confirmation.'],
    documents: ['Degree certificate or proof of expected graduation.', 'Transcript and grading explanation where requested.', 'CV, motivation statement, and references in the required format.', 'Passport and language evidence if the call requests them.'],
    mistakes: ['Assuming every programme has identical scholarship coverage.', 'Using a generic statement that does not address the consortium’s study tracks.', 'Paying an agent for a guaranteed scholarship.'],
    caveat: 'Participating programmes, scholarship numbers, deadlines, and eligibility are call-specific. Confirm whether a fee, residence document, or additional national visa step applies.',
  },
  {
    title: 'EURES Cross-Border Job Search: A Safer Workflow for EU Applicants',
    slug: 'eures-cross-border-job-search-guide',
    category: 'Europe Careers',
    focusKeyword: 'EURES jobs for foreigners',
    excerpt: 'Use the EU employment network to compare vacancies, mobility advice, and work-right information before relocating.',
    sourceUrl: 'https://eures.europa.eu/index_en',
    answer: 'EURES helps people search participating European vacancies and find mobility advisers. A listing is not a work permit, and the employer still decides whom to hire. Use the portal to verify the vacancy and then check the destination country’s official rules.',
    steps: ['Create a profile only on the EURES domain and search by occupation, language, and location.', 'Read the full vacancy, employer identity, contract, and application method.', 'Ask a EURES adviser about cross-border social security or mobility questions.', 'Confirm residence, tax, and professional-recognition steps with national authorities.'],
    documents: ['CV adapted to the vacancy and local language expectations.', 'Evidence of qualifications and professional registration.', 'Identity and right-to-work evidence when requested after a genuine offer.', 'Written offer stating employer, duties, place, and pay.'],
    mistakes: ['Treating a third-party repost as proof a role is still open.', 'Paying for a “guaranteed EURES job”.', 'Moving before checking regulated-profession recognition.'],
    caveat: 'Free-movement rights and national work authorisation depend on nationality and status. Vacancy data and adviser availability change; verify before travel.',
  },
  {
    title: 'Europass Digital Credentials: How to Share Verifiable Learning Evidence',
    slug: 'europass-digital-credentials-sharing-guide',
    category: 'Europe Careers',
    focusKeyword: 'Europass digital credentials',
    excerpt: 'A practical guide to checking, storing, and sharing European digital learning credentials without exposing unnecessary data.',
    sourceUrl: 'https://europa.eu/europass/en/digital-credentials',
    answer: 'Europass digital credentials are electronic records issued by an authorised organisation. They can help a recruiter or institution verify learning, but they do not automatically equal professional recognition or admission.',
    steps: ['Open the credential from the issuer or Europass wallet and check the issuer name.', 'Read the qualification, achievement, validity, and verification information.', 'Share the verification link or file requested by the recipient.', 'Keep a backup and ask the issuer to correct errors rather than editing the credential yourself.'],
    documents: ['The original credential file or wallet record.', 'Issuer contact and award reference.', 'Supporting transcript or certificate if the recipient requests it.', 'Consent from the credential holder before sharing personal data.'],
    mistakes: ['Uploading a screenshot when a recipient needs the verification link.', 'Assuming a digital badge proves a licence to practise.', 'Sharing a wallet link publicly where personal data is visible.'],
    caveat: 'Issuer practices and recipient acceptance differ. Check the university, employer, or regulator’s current evidence policy.',
  },
  {
    title: 'UK DBS Check for Overseas Applicants: What the Employer Can Actually Request',
    slug: 'uk-dbs-check-overseas-applicant-process',
    category: 'UK Procedures',
    focusKeyword: 'UK DBS check overseas applicant',
    excerpt: 'Understand employer-led Disclosure and Barring Service checks and why overseas police certificates may also be needed.',
    sourceUrl: 'https://www.gov.uk/government/organisations/disclosure-and-barring-service',
    answer: 'A DBS check is normally requested by an eligible employer or organisation, not bought independently as a visa guarantee. People who lived abroad may also need overseas criminal-record evidence because a DBS certificate does not generally cover time outside the UK.',
    steps: ['Ask the employer which DBS level and role eligibility applies.', 'Provide identity and address evidence through the employer’s authorised process.', 'List overseas residence accurately and ask what foreign certificate is accepted.', 'Review the certificate and raise an error through the official route.'],
    documents: ['Current identity document and address history.', 'Evidence of UK address where required.', 'Overseas police certificate or explanation if the relevant country cannot issue one.', 'Employer’s written request and role details.'],
    mistakes: ['Using a website that promises an instant DBS certificate.', 'Leaving gaps in address history.', 'Assuming a clean DBS replaces immigration or professional checks.'],
    caveat: 'The employer chooses the lawful level of check and overseas evidence. Processing, identity rules, and guidance can change; follow the current GOV.UK pages.',
  },
  {
    title: 'Parcoursup for International Applicants: A Document-First Checklist',
    slug: 'parcoursup-international-applicant-checklist',
    category: 'France Admissions',
    focusKeyword: 'Parcoursup international student',
    excerpt: 'How to verify French undergraduate application requirements, language evidence, and conditional offers.',
    sourceUrl: 'https://www.parcoursup.gouv.fr/',
    answer: 'Parcoursup is France’s national platform for many first-year higher-education applications. The course page and the applicant’s nationality and residence determine whether another procedure, such as a visa-related application, is also needed.',
    steps: ['Create the account during the published period and identify every course deadline.', 'Read each fiche formation for prerequisites, language, documents, and selection method.', 'Enter education history exactly as shown on official records.', 'Complete required confirmations and monitor messages inside the account.'],
    documents: ['Passport or identity evidence.', 'School transcripts, predicted results, and translations if requested.', 'Language certificate or schooling proof where listed.', 'Visa or residence evidence only when the relevant authority asks.'],
    mistakes: ['Confusing a course’s application deadline with the visa deadline.', 'Copying grades into the form without checking the grading scale.', 'Missing a confirmation button after saving an application.'],
    caveat: 'Courses, calendars, fees, and procedures are updated each cycle. The institution and French authorities decide final admission and immigration requirements.',
  },
  {
    title: 'Germany Anmeldung: A Newcomer’s Address-Registration Checklist',
    slug: 'germany-anmeldung-address-registration-guide',
    category: 'Germany Procedures',
    focusKeyword: 'Germany Anmeldung registration',
    excerpt: 'What to prepare before registering a German address and how to avoid common landlord-certificate errors.',
    sourceUrl: 'https://www.make-it-in-germany.com/en/living-in-germany/housing/registering-your-address',
    answer: 'People who move into accommodation in Germany generally register with the local registration office under the conditions explained by the official Make it in Germany guidance. The exact office, appointment system, and timing are local.',
    steps: ['Find the Bürgeramt responsible for the address and book or confirm its appointment method.', 'Ask the landlord or provider for the Wohnungsgeberbestätigung.', 'Bring identity documents and any local form required.', 'Check the registration certificate before leaving and use it for later services only when requested.'],
    documents: ['Passport or national identity card.', 'Completed local registration form if required.', 'Signed Wohnungsgeberbestätigung.', 'Residence documents for family members where applicable.'],
    mistakes: ['Using a rental contract instead of the required landlord confirmation.', 'Registering an address where you do not actually live.', 'Assuming registration itself grants a residence permit or tax status.'],
    caveat: 'Municipal offices set appointments and may have local-language forms. Confirm deadlines, exemptions, and change-of-address rules with the responsible municipality.',
  },
  {
    title: 'Germany Ausbildung Search: Verify Training Contracts Before Applying',
    slug: 'germany-ausbildung-training-contract-verification',
    category: 'Germany Careers',
    focusKeyword: 'Germany Ausbildung application',
    excerpt: 'A source-first way to compare dual vocational training vacancies, language expectations, and residence steps.',
    sourceUrl: 'https://www.make-it-in-germany.com/en/study-training/training-in-germany',
    answer: 'Ausbildung can mean different vocational routes. Start with the official explanation, then verify the occupation, training company, school component, language level, pay, and immigration route in the actual contract and official visa guidance.',
    steps: ['Choose an occupation from the official training information and understand its duration and assessment.', 'Apply to named companies or chambers using their stated process.', 'Check the contract for occupation, start date, location, pay, and school details.', 'Only after a genuine contract, check the visa and residence requirements.'],
    documents: ['School certificates and translated records if requested.', 'Language evidence required by the employer or authority.', 'CV and references tailored to the occupation.', 'Signed training contract and identity documents for later residence steps.'],
    mistakes: ['Paying a recruiter for a “guaranteed Ausbildung visa”.', 'Confusing a private course with a recognised training contract.', 'Ignoring shift, accommodation, or school attendance obligations.'],
    caveat: 'Recognition, language, salary thresholds, and visa rules are time-sensitive and occupation-specific. The embassy and immigration office have final authority.',
  },
  {
    title: 'Netherlands DigiD for New Residents: Activation and Safe Use',
    slug: 'netherlands-digid-new-resident-guide',
    category: 'Netherlands Digital Services',
    focusKeyword: 'DigiD application Netherlands',
    excerpt: 'How to request, activate, and protect the Dutch digital identity used for public services.',
    sourceUrl: 'https://www.digid.nl/en/',
    answer: 'DigiD is a personal login for Dutch government and participating services. It is not a residence permit, bank identity, or shareable account. Follow DigiD’s own application and activation instructions and protect the activation code.',
    steps: ['Check the identity and registration conditions on DigiD.nl.', 'Request the login using your own details and wait for the official letter or code.', 'Activate within the stated period and add the available security method.', 'Use the official login page and sign out on shared devices.'],
    documents: ['Citizen service number and registered address if required.', 'Identity document used for the request.', 'Activation letter or code.', 'Recovery details kept securely and never sent to another person.'],
    mistakes: ['Giving a DigiD password to an employer or consultant.', 'Clicking a look-alike SMS link.', 'Waiting until a tax or benefits deadline to request activation.'],
    caveat: 'Eligibility, delivery, app features, and recovery rules can change. Contact DigiD through its official help pages if a letter is lost or an account is compromised.',
  },
  {
    title: 'Portugal NIF for Newcomers: A Verification-First Tax Number Guide',
    slug: 'portugal-nif-newcomer-tax-number-guide',
    category: 'Portugal Procedures',
    focusKeyword: 'Portugal NIF application',
    excerpt: 'Understand why a Portuguese tax number is requested and how to use official tax-authority channels.',
    sourceUrl: 'https://www.portaldasfinancas.gov.pt/at/html/index.html',
    answer: 'The NIF is a Portuguese tax identification number used in many financial and administrative interactions. The Tax and Customs Authority (AT) sets the application route and evidence; obtaining a NIF does not by itself confer residence or tax residency.',
    steps: ['Read AT’s current taxpayer-registration instructions and identify the applicable applicant category.', 'Use an AT office or the official online route described there.', 'Provide identity, address, and representative evidence only when required for your case.', 'Keep the issued confirmation and update details through AT when they change.'],
    documents: ['Passport or accepted identity document.', 'Proof of address in the format AT accepts.', 'Tax-representative evidence if the current rule requires one.', 'Appointment or online-request reference.'],
    mistakes: ['Paying an unofficial site for a number that AT issues.', 'Calling a NIF a residence permit.', 'Using an old address and missing tax correspondence.'],
    caveat: 'Rules for residents, non-residents, online applications, and representatives may change. Get tax advice for residency and filing questions.',
  },
  {
    title: 'Italy SPID: Choosing an Authorised Identity Provider and Recovering Access',
    slug: 'italy-spid-authorised-provider-guide',
    category: 'Italy Digital Services',
    focusKeyword: 'Italy SPID application',
    excerpt: 'A practical checklist for obtaining Italy’s public digital identity through an authorised provider.',
    sourceUrl: 'https://www.spid.gov.it/',
    answer: 'SPID is issued by accredited identity providers and is used for participating Italian public services. Applicants should compare providers on the official portal, complete identity verification, and treat credentials as private.',
    steps: ['Read the official SPID requirements and list of accredited providers.', 'Choose a provider whose identification method and support suit you.', 'Submit identity and contact details through that provider’s official domain.', 'Test login on a service you need and use the provider’s recovery process if access fails.'],
    documents: ['Valid identity document and health card or accepted equivalent.', 'Personal email address and mobile number.', 'Video, in-person, or electronic identification evidence as selected.', 'Provider confirmation and recovery codes.'],
    mistakes: ['Selecting a provider from an advertisement without checking accreditation.', 'Letting an agent retain your password or one-time code.', 'Assuming SPID proves immigration status.'],
    caveat: 'Provider prices, identification methods, and supported services differ. Check current AgID/SPID instructions and accessibility options.',
  },
  {
    title: 'Kenya eCitizen Passport Application: A Document and Appointment Checklist',
    slug: 'kenya-ecitizen-passport-application-checklist',
    category: 'Kenya Government Services',
    focusKeyword: 'Kenya eCitizen passport application',
    excerpt: 'Use Kenya’s official eCitizen and immigration information to prepare a passport application without relying on brokers.',
    sourceUrl: 'https://immigration.go.ke/passport-application/',
    answer: 'Kenyan passport applications are initiated through the government’s stated digital and appointment process. The Directorate of Immigration Services determines document, biometric, collection, and replacement requirements.',
    steps: ['Read the current passport category and document list on immigration.go.ke.', 'Create or use your own eCitizen account and complete the form accurately.', 'Pay only through the official payment flow and retain the receipt.', 'Attend the selected centre for biometrics and collect only after the official notification.'],
    documents: ['Birth certificate or registration evidence listed for your category.', 'National identity card where required.', 'Parents’ or guarantor evidence when the official checklist requests it.', 'Previous passport and police report for replacement cases, if applicable.'],
    mistakes: ['Using a broker’s phone number or account.', 'Booking biometrics before checking the centre and required originals.', 'Assuming payment guarantees approval.'],
    caveat: 'Fees, appointment availability, collection locations, and processing times are subject to official updates. Follow the current notice for minors and lost passports.',
  },
  {
    title: 'South Africa Apostille and Authentication: Which Route Fits Your Document',
    slug: 'south-africa-apostille-authentication-guide',
    category: 'South Africa Procedures',
    focusKeyword: 'South Africa apostille certificate',
    excerpt: 'A decision guide for authenticating South African public documents for use abroad.',
    sourceUrl: 'https://www.dirco.gov.za/consular-services/apostilles-and-authentication/',
    answer: 'Whether a South African document needs an apostille or authentication depends on the destination country and the document type. DIRCO’s consular guidance explains the official route; the receiving authority decides what it will accept.',
    steps: ['Ask the foreign university, employer, court, or authority what certification it requires.', 'Check whether the destination is covered by the Apostille Convention for your use case.', 'Prepare the original or acceptable certified document and follow DIRCO submission instructions.', 'Send the completed certificate with any required translation to the recipient.'],
    documents: ['Original public document or the form of copy DIRCO accepts.', 'Identity and appointment evidence if required.', 'Translation from an accepted translator when the recipient requires it.', 'Written destination-country instructions.'],
    mistakes: ['Obtaining a notary stamp and assuming it is an apostille.', 'Authenticating the wrong version of a certificate.', 'Ignoring the recipient’s language or validity requirements.'],
    caveat: 'Office locations, fees, appointment systems, and turnaround times can change. Authentication does not prove the truth of every statement in a document.',
  },
  {
    title: 'South Africa NSFAS Funding: Verify Application and Appeal Evidence',
    slug: 'south-africa-nsfas-application-appeal-guide',
    category: 'South Africa Education',
    focusKeyword: 'NSFAS application appeal',
    excerpt: 'How students can use official NSFAS channels, protect personal data, and assemble an appeal record.',
    sourceUrl: 'https://www.nsfas.org.za/',
    answer: 'NSFAS funding decisions depend on the published rules and information verified for the relevant academic cycle. Apply through NSFAS, monitor the portal, and use the stated appeal process if the decision permits one.',
    steps: ['Read the current funding and application announcement.', 'Create a personal account and upload clear, correctly named documents.', 'Check status messages and respond to requests before the portal deadline.', 'If eligible to appeal, select the stated reason and attach evidence that addresses it.'],
    documents: ['Identity document and household information requested by the cycle.', 'Academic or registration evidence from the institution.', 'Proof supporting changed circumstances or an appeal reason.', 'Screenshots and reference numbers for portal problems.'],
    mistakes: ['Paying someone to “unlock” funding.', 'Uploading unrelated documents instead of evidence for the rejection reason.', 'Assuming an application equals registration or accommodation funding.'],
    caveat: 'Eligibility, allowances, participating institutions, and dates are cycle-specific. Confirm announcements on nsfas.org.za and with your institution’s financial-aid office.',
  },
  {
    title: 'Nigeria JAMB UTME: Profile Code, Direct Entry, and Result Verification',
    slug: 'nigeria-jamb-utme-official-process',
    category: 'Nigeria Exams',
    focusKeyword: 'JAMB UTME registration',
    excerpt: 'A source-first workflow for Nigerian candidates comparing UTME, Direct Entry, biometric capture, and result services.',
    sourceUrl: 'https://www.jamb.gov.ng/',
    answer: 'JAMB publishes the current UTME and Direct Entry bulletin, approved registration channels, examination rules, and result services. Candidates should use the bulletin for the relevant year because dates, fees, and required credentials are not permanent.',
    steps: ['Read the year’s official bulletin and create the required profile code through the stated channel.', 'Use an approved registration centre for biometrics and data capture.', 'Review institution and programme choices before final submission.', 'Use JAMB’s official result and admission-status services, then follow the institution’s acceptance process.'],
    documents: ['National identity or approved identification evidence.', 'O-level results and permitted result details.', 'Email, phone, and profile-code records.', 'Direct Entry qualification documents where that route applies.'],
    mistakes: ['Using an unapproved cybercafe or copied payment link.', 'Choosing a course without checking the institution’s requirements.', 'Sharing profile codes or one-time passwords.'],
    caveat: 'JAMB sets the operative calendar, fees, centres, and subject rules each cycle. A result does not guarantee admission; institutions and CAPS processes still apply.',
  },
  {
    title: 'Ghana Tertiary Admissions: Centralised Application Checks for Applicants',
    slug: 'ghana-tertiary-admissions-application-guide',
    category: 'Ghana Admissions',
    focusKeyword: 'Ghana university admission application',
    excerpt: 'How to compare Ghanaian tertiary programmes and verify application instructions with the institution.',
    sourceUrl: 'https://www.gtec.edu.gh/',
    answer: 'Ghanaian applicants should begin with the institution’s official admissions page and use Ghana Tertiary Education Commission information to check recognised providers. Each university or college controls its programme requirements, calendar, and payment instructions.',
    steps: ['Confirm the institution and programme appear in official recognition information.', 'Read the institution’s current prospectus for subjects, grades, mature-entry rules, and documents.', 'Complete the official form, upload evidence, and verify the generated application summary.', 'Track admission and accept only through the institution’s stated portal.'],
    documents: ['WASSCE or equivalent results and index details.', 'Identity document and passport photo in the required format.', 'Transcripts, references, or mature-applicant evidence where listed.', 'Payment receipt and application reference.'],
    mistakes: ['Relying on an agent’s list of “guaranteed” admissions.', 'Paying into a personal mobile-money number.', 'Applying to an unrecognised programme because its advertising looks official.'],
    caveat: 'Admissions, fees, cut-offs, and calendars change by institution and cycle. Confirm recognition and programme accreditation before paying.',
  },
  {
    title: 'Rwanda Irembo Services: A Safe Workflow for Online Government Requests',
    slug: 'rwanda-irembo-online-government-services',
    category: 'Rwanda Digital Services',
    focusKeyword: 'Irembo government services',
    excerpt: 'Use Rwanda’s official digital service gateway to identify forms, payments, and collection instructions.',
    sourceUrl: 'https://irembo.gov.rw/',
    answer: 'Irembo is Rwanda’s government service gateway for selected applications. The service page tells you the responsible agency, eligibility, required evidence, fee if any, and how an application is completed.',
    steps: ['Search the exact service and read its requirements before creating a request.', 'Enter applicant data exactly as on identity records and select the correct service centre.', 'Pay only through the payment methods shown in Irembo.', 'Save the application number and respond to agency messages or collection instructions.'],
    documents: ['National ID, passport, or other evidence specified by the service.', 'Supporting certificates in the accepted format.', 'Phone number and email that you control.', 'Payment receipt and application number.'],
    mistakes: ['Choosing a similarly named service for a different agency.', 'Giving a service agent control of your account credentials.', 'Arriving for collection without checking status.'],
    caveat: 'Service availability, fees, processing, and agency requirements are updated online. Irembo support can explain a portal issue but cannot change an agency decision.',
  },
  {
    title: 'Egypt Study in Egypt: Verify International Student Admission Steps',
    slug: 'egypt-study-in-egypt-international-admission',
    category: 'Egypt Admissions',
    focusKeyword: 'Study in Egypt international admission',
    excerpt: 'A practical way for international applicants to compare Egyptian universities and follow the official admission route.',
    sourceUrl: 'https://admission.study-in-egypt.gov.eg/',
    answer: 'International applicants should use the Study in Egypt platform and the chosen university’s own page to confirm programmes, documents, and payment instructions. A platform submission is not a guarantee of admission or a visa.',
    steps: ['Search the official platform for eligible institutions and programmes.', 'Check degree equivalence, language, transcript, and health-document instructions.', 'Create the applicant record, upload legible documents, and review choices.', 'After an offer, verify enrolment, residence, and visa steps with the university and Egyptian authorities.'],
    documents: ['Passport and recent photograph.', 'Secondary or university certificate and transcript.', 'Legalisation or translation only if the current instructions require it.', 'Offer and payment confirmations.'],
    mistakes: ['Sending money to a personal account advertised as a university fee.', 'Assuming a programme is taught in English without checking the course page.', 'Travelling before receiving written admission guidance.'],
    caveat: 'Programme lists, deadlines, fees, equivalency, and visa rules can change. The university and competent Egyptian authorities decide the final outcome.',
  },
  {
    title: 'Morocco ANAPEC Job Search: Verify Offers and Work-Authorisation Claims',
    slug: 'morocco-anapec-job-search-verification',
    category: 'Morocco Careers',
    focusKeyword: 'ANAPEC jobs Morocco',
    excerpt: 'How to use Morocco’s employment agency information while checking employer identity and overseas recruitment claims.',
    sourceUrl: 'https://www.anapec.org/',
    answer: 'ANAPEC provides employment and placement services, including information for some international opportunities. Applicants must still verify the named employer, contract, salary, destination-country permission, and any charge before accepting.',
    steps: ['Search the official ANAPEC service or vacancy information.', 'Confirm the employer and vacancy reference independently on the employer’s domain.', 'Read the contract in a language you understand and ask about deductions.', 'Check destination-country work authorisation through its government or embassy.'],
    documents: ['CV and identity document only when the official process requests them.', 'Qualification or experience evidence.', 'Written contract naming employer, location, duties, and pay.', 'Work-permit or visa information from the destination authority.'],
    mistakes: ['Paying for a job, invitation, or visa guarantee.', 'Handing over a passport to an intermediary.', 'Ignoring recruitment-country rules because a vacancy appears on social media.'],
    caveat: 'Vacancies and bilateral placement arrangements change. ANAPEC cannot guarantee a foreign employer’s conduct or a destination-country visa decision.',
  },
  {
    title: 'UAE MOHRE Employment Contract: What Workers Should Verify',
    slug: 'uae-mohre-employment-contract-verification',
    category: 'UAE Employment',
    focusKeyword: 'UAE MOHRE employment contract',
    excerpt: 'A worker-focused checklist for comparing an offer with the contract recorded through UAE labour channels.',
    sourceUrl: 'https://www.mohre.gov.ae/',
    answer: 'Before starting private-sector work in the UAE, compare the signed offer and the employment contract handled through the official labour process. Jobseekers should verify employer identity, salary, duties, probation, leave, and who is responsible for lawful permit steps.',
    steps: ['Read the offer in full and ask for a copy before travelling.', 'Check the employer and contract details through MOHRE or the authorised channel.', 'Do not sign blank pages or pay a fee for a guaranteed job.', 'Keep wage, complaint, and contract records and use MOHRE support if terms differ.'],
    documents: ['Passport shown only through a secure, legitimate process.', 'Written offer and contract copy.', 'Qualification or professional licence where the role requires it.', 'Receipts and messages relating to recruitment or deductions.'],
    mistakes: ['Accepting a lower salary than the signed offer without clarification.', 'Working for a different employer from the authorised sponsor.', 'Assuming a tourist entry permits employment.'],
    caveat: 'UAE labour, permit, and complaint procedures vary by sector and can be updated. MOHRE and the relevant free-zone authority are the proper sources.',
  },
  {
    title: 'Saudi Absher Services: Identity-Safe Government Procedure Checklist',
    slug: 'saudi-absher-government-services-safe-use',
    category: 'Saudi Digital Services',
    focusKeyword: 'Absher government services guide',
    excerpt: 'How residents can identify the correct Absher service, protect verification codes, and retain transaction evidence.',
    sourceUrl: 'https://www.absher.sa/',
    answer: 'Absher provides Saudi government e-services for eligible users. Use the service description and official help channels to understand prerequisites; an Absher account or appointment does not itself approve a separate immigration or licensing request.',
    steps: ['Enter the official Absher address yourself and select the relevant service.', 'Read prerequisites, identity verification, and appointment or payment instructions.', 'Complete the request using your own account and never disclose a verification code.', 'Save the transaction number and check status in the account.'],
    documents: ['Valid identity or residence details requested in the service.', 'Service-specific evidence in the required format.', 'Mobile number registered to the account where required.', 'Transaction receipt and appointment details.'],
    mistakes: ['Following an unofficial “Absher activation” link.', 'Letting a broker keep account access.', 'Missing an appointment because the confirmation was not saved.'],
    caveat: 'Services, eligibility, Arabic/English availability, and fees are controlled by the responsible Saudi authority. Check current terms before acting.',
  },
  {
    title: 'Qatar Hukoomi: Find the Correct Government Service and Escalation Route',
    slug: 'qatar-hukoomi-government-service-guide',
    category: 'Qatar Digital Services',
    focusKeyword: 'Qatar Hukoomi services',
    excerpt: 'A practical method for using Qatar’s government portal for forms, requirements, and service contacts.',
    sourceUrl: 'https://hukoomi.gov.qa/en',
    answer: 'Hukoomi is Qatar’s official government information gateway. It helps users locate the responsible ministry, prerequisites, forms, and contact route; the ministry or service portal remains responsible for the decision.',
    steps: ['Search by service name and read the eligibility and required-documents section.', 'Follow the linked ministry or digital-service portal rather than an advertisement.', 'Submit with the account and identity method specified for the service.', 'Keep the reference number and use the listed complaint or help channel if delayed.'],
    documents: ['QID, passport, or other identity evidence as specified.', 'Employer, school, tenancy, or family evidence for the chosen service.', 'Arabic translation or attestation only when required.', 'Receipt, reference, and appointment confirmation.'],
    mistakes: ['Choosing a service from an outdated blog.', 'Uploading sensitive files to a non-government domain.', 'Assuming information pages are an approval.'],
    caveat: 'Service eligibility and digital channels can change. Confirm the latest instruction with the linked ministry, especially for immigration and employment matters.',
  },
  {
    title: 'WHO Academy Certificates: Verify Completion and Use of Health Training',
    slug: 'who-academy-certificate-verification-guide',
    category: 'International Certifications',
    focusKeyword: 'WHO Academy certificate',
    excerpt: 'How learners can distinguish a WHO learning certificate from a professional licence or national qualification.',
    sourceUrl: 'https://www.who.int/about/accountability/governance/who-academy',
    answer: 'A WHO Academy or WHO learning certificate records completion of a particular learning activity. It may support professional development, but an employer, regulator, or university decides whether it counts toward its own requirement.',
    steps: ['Register through the official WHO learning page and read the course description.', 'Check assessment, attendance, completion, and certificate conditions before starting.', 'Download the issued certificate from the learner account and verify the issuer details.', 'Ask the receiving organisation in advance how it evaluates the certificate.'],
    documents: ['Account email and identity details required by the course.', 'Completion or assessment evidence shown in the platform.', 'Certificate ID or verification link.', 'Separate licence or degree evidence if the recipient requires it.'],
    mistakes: ['Buying a copied certificate from a social-media seller.', 'Calling a short course a clinical licence.', 'Assuming every WHO-branded resource is an accredited qualification.'],
    caveat: 'Course availability, assessment, language, and recognition vary. Check the specific course and the rules of the national regulator or employer.',
  },
  {
    title: 'Cisco Certification Scheduling: A Candidate’s Official Exam-Booking Checklist',
    slug: 'cisco-certification-exam-booking-guide',
    category: 'International Certifications',
    focusKeyword: 'Cisco certification exam registration',
    excerpt: 'Prepare for a Cisco certification exam by checking the current blueprint, identity rules, and authorised delivery options.',
    sourceUrl: 'https://www.cisco.com/c/en/us/training-events/training-certifications/certifications.html',
    answer: 'Cisco publishes certification tracks and exam information, while authorised testing partners handle scheduling. Candidates should choose the current exam, read its blueprint, and verify delivery, identification, rescheduling, and score-report rules before paying.',
    steps: ['Select the certification and open the current exam page and blueprint.', 'Create the required Cisco and testing-partner accounts with matching names.', 'Choose an authorised test-centre or online option and review its rules.', 'After the exam, retain the score report and use Cisco’s certification account for status.'],
    documents: ['Government ID matching the booking name.', 'Exam blueprint and learning plan.', 'Accessibility accommodation request, if needed, before booking.', 'Payment and appointment confirmation.'],
    mistakes: ['Studying from a retired exam code.', 'Booking with a nickname that does not match identity evidence.', 'Using “exam dumps” that breach certification rules.'],
    caveat: 'Exam codes, prices, delivery, retake, and renewal policies change. Cisco and the authorised testing provider control the live terms.',
  },
  {
    title: 'CompTIA Certification Renewal: CEUs, Fees, and Audit Evidence',
    slug: 'comptia-certification-renewal-ceus-guide',
    category: 'International Certifications',
    focusKeyword: 'CompTIA certification renewal',
    excerpt: 'A records-first guide to keeping a CompTIA certification current through the official continuing-education process.',
    sourceUrl: 'https://www.comptia.org/certifications/renew-your-certification',
    answer: 'CompTIA certifications have certification-specific renewal rules. The official renewal page explains whether continuing education, a higher certification, or another route applies; do not rely on a training seller’s promise that any course renews every credential.',
    steps: ['Open the renewal page for the exact certification and expiration date.', 'Map each activity to the accepted continuing-education category before paying.', 'Upload the required evidence and pay only through the official account if a fee applies.', 'Monitor the account for approval and retain audit records.'],
    documents: ['Certification ID and expiry information.', 'Course completion, work, or project evidence accepted by the programme.', 'Dates, provider, and learning detail for each activity.', 'Receipts and submission confirmation.'],
    mistakes: ['Claiming the same activity twice.', 'Uploading a certificate without dates or learning detail.', 'Waiting until after expiry without checking reinstatement rules.'],
    caveat: 'Accepted activities, renewal fees, and deadlines depend on the certification and current CompTIA policy. Read the live page before planning CEUs.',
  },
  {
    title: 'UK ENIC Statement of Comparability: When Employers Need It',
    slug: 'uk-enic-statement-of-comparability-guide',
    category: 'UK Qualifications',
    focusKeyword: 'UK ENIC statement of comparability',
    excerpt: 'How to decide whether a UK ENIC statement helps an employer, university, or regulator assess an overseas award.',
    sourceUrl: 'https://www.enic.org.uk/individuals/statement-of-comparability',
    answer: 'A UK ENIC Statement of Comparability explains how an international qualification compares to UK education frameworks. It is evidence for a recipient, not a professional licence, admission decision, or guarantee that an employer will accept the award.',
    steps: ['Ask the recipient whether it requires UK ENIC and which service is acceptable.', 'Check the current document, translation, and verification requirements.', 'Submit through the official UK ENIC account and monitor requests.', 'Send the statement together with the original award and transcript when asked.'],
    documents: ['Final certificate and transcript.', 'Identity evidence and name-change proof.', 'Accepted translation where documents are not in English.', 'Award verification contact or consent if the institution must be contacted.'],
    mistakes: ['Ordering a statement for a regulated job instead of contacting the regulator.', 'Uploading provisional results when a final award is required.', 'Assuming the comparison states the subject or professional competence.'],
    caveat: 'Prices, processing, accepted documents, and recipient policies change. Check the official UK ENIC service before ordering.',
  },
  {
    title: 'EU Blue Card Information: Compare the Official National Application Route',
    slug: 'eu-blue-card-national-application-route',
    category: 'Migration Procedures',
    focusKeyword: 'EU Blue Card requirements',
    excerpt: 'A careful starting point for highly qualified workers comparing EU Blue Card rules in different member states.',
    sourceUrl: 'https://immigration-portal.ec.europa.eu/eu-blue-card_en',
    answer: 'The EU Blue Card is implemented through national procedures. The EU Immigration Portal explains the concept and links country information, but salary thresholds, contract length, documents, mobility, and family rules must be checked for the chosen country.',
    steps: ['Choose the member state and open its country-specific Blue Card page.', 'Check the occupation, qualification, contract, salary, insurance, and labour-market conditions.', 'Follow the employer or applicant filing route named by the authority.', 'After approval, follow registration and family-reunification instructions separately.'],
    documents: ['Passport and compliant photograph.', 'Recognised qualification or evidence of higher professional skills.', 'Signed employment contract or binding offer.', 'Insurance, accommodation, and criminal-record evidence when the national authority requests them.'],
    mistakes: ['Applying under a generic “EU visa” rather than a national authority route.', 'Using an old salary figure copied from a forum.', 'Working for a different role or employer without checking permission.'],
    caveat: 'Member states set and update their own thresholds, fees, processing, and exceptions. An official portal page is not legal advice.',
  },
  {
    title: 'UK Skilled Worker Visa: Link the Job, Sponsor, and Evidence Correctly',
    slug: 'uk-skilled-worker-visa-evidence-checklist',
    category: 'Migration Procedures',
    focusKeyword: 'UK Skilled Worker visa checklist',
    excerpt: 'A document-first workflow for checking sponsorship, occupation, salary, English, and application evidence.',
    sourceUrl: 'https://www.gov.uk/skilled-worker-visa',
    answer: 'A Skilled Worker application depends on the specific job, licensed sponsor, certificate of sponsorship, salary rules, and applicant evidence. GOV.UK is the source for the current eligible occupations, fees, and financial requirements.',
    steps: ['Confirm the employer appears on the official sponsor register and the job is eligible.', 'Check the certificate of sponsorship details against the offer.', 'Assemble identity, English, maintenance, and criminal-record evidence where required.', 'Submit the application and biometrics through the current GOV.UK route.'],
    documents: ['Passport and certificate of sponsorship reference.', 'Job title, occupation code, salary, and contract details.', 'English-language evidence or exemption evidence.', 'Translations and financial evidence in the required format.'],
    mistakes: ['Paying for sponsorship or a guaranteed visa.', 'Using the wrong occupation code.', 'Assuming a sponsor’s email replaces the certificate of sponsorship.'],
    caveat: 'Rules, salary tables, fees, and eligible occupations change. Read the current GOV.UK page and obtain regulated advice for a complex case.',
  },
  {
    title: 'Schengen Short-Stay Visa: Build a Consistent Application File',
    slug: 'schengen-short-stay-visa-application-file',
    category: 'Migration Procedures',
    focusKeyword: 'Schengen visa application documents',
    excerpt: 'A practical checklist for choosing the correct consulate and presenting consistent travel evidence.',
    sourceUrl: 'https://home-affairs.ec.europa.eu/policies/schengen-borders-and-visa/visa-policy_en',
    answer: 'A Schengen short-stay visa application is submitted to the consulate responsible under the destination rules, not automatically to whichever centre has the earliest appointment. The applicant must show the purpose, itinerary, means, insurance, and intention to comply with the authorised stay.',
    steps: ['Identify the correct consulate from the main destination or other applicable rule.', 'Read its current checklist and complete the authorised application form.', 'Book biometrics through the consulate’s named provider.', 'Carry copies of the submitted file and follow the decision or appeal instructions.'],
    documents: ['Passport meeting the stated validity and blank-page rules.', 'Itinerary, accommodation, invitation, or event evidence as applicable.', 'Travel medical insurance meeting the current requirement.', 'Financial, employment, study, and return-ties evidence appropriate to the case.'],
    mistakes: ['Submitting inconsistent dates across bookings and forms.', 'Buying non-refundable travel solely because a visa is pending.', 'Using a fake reservation or unverified agent.'],
    caveat: 'Consulates set checklists, appointment capacity, fees, and processing information within the common framework. Verify before booking travel.',
  },
  {
    title: 'International Credential Evaluation: Keep University Applications Verifiable',
    slug: 'international-credential-evaluation-verification',
    category: 'International Admissions',
    focusKeyword: 'international credential evaluation',
    excerpt: 'How applicants can compare university requests for transcripts, verification, translations, and evaluation reports.',
    sourceUrl: 'https://www.unesco.org/en/education/higher-education/conventions',
    answer: 'Credential evaluation is recipient-specific: a university, licensing body, or immigration authority may require direct transcripts, a recognised evaluator, or a government recognition statement. Ask the recipient before ordering an expensive report.',
    steps: ['Read the receiving institution’s international-admissions page and identify the exact evidence requested.', 'Check whether documents must be sent directly by the awarding institution.', 'Use only an evaluator or authority named or accepted by the recipient.', 'Submit the report with the original academic record and explain any grading-scale issue.'],
    documents: ['Award certificate and complete transcript.', 'Institutional grading-scale explanation.', 'Certified translation if required.', 'Identity and name-change evidence.'],
    mistakes: ['Ordering the wrong evaluation type.', 'Using a report accepted by one university as proof it is accepted everywhere.', 'Altering or compressing a transcript so security features disappear.'],
    caveat: 'Recognition conventions, evaluator lists, fees, and turnaround times differ. The receiving institution’s current written instruction controls.',
  },
  {
    title: 'Ireland Safe Pass and Construction Training: Check the Correct Provider',
    slug: 'ireland-safe-pass-construction-training-guide',
    category: 'Ireland Certifications',
    focusKeyword: 'Ireland Safe Pass course',
    excerpt: 'How construction workers can verify the required safety training, card status, and approved training route in Ireland.',
    sourceUrl: 'https://www.hsa.ie/eng/your_industry/construction/safe_pass/',
    answer: 'Safe Pass is a health-and-safety awareness programme for construction workers in Ireland, but the employer and Health and Safety Authority guidance determine when it is required. A card is not a work permit, trade qualification, or guarantee of employment.',
    steps: ['Read the HSA explanation and identify whether your work and site require Safe Pass.', 'Book only with a provider accepted under the current scheme.', 'Bring the identity evidence and complete the attendance and assessment requirements.', 'Give the employer the card details and renew or replace it through the stated route when necessary.'],
    documents: ['Accepted photo identity document.', 'Course booking confirmation and provider details.', 'Existing card for replacement or renewal questions.', 'Separate trade, permit, or right-to-work evidence requested by the employer.'],
    mistakes: ['Buying a card without attending the course.', 'Confusing Safe Pass with a Safe Pass equivalent from another country.', 'Starting work before checking the site’s induction and other training requirements.'],
    caveat: 'Course providers, card rules, fees, and renewal arrangements can change. The HSA and employer’s current site requirements control.',
  },
  {
    title: 'Kenya HELB Loan Application: Keep Funding and Repayment Records',
    slug: 'kenya-helb-loan-application-guide',
    category: 'Kenya Education',
    focusKeyword: 'HELB loan application',
    excerpt: 'A practical checklist for Kenyan students comparing HELB funding, evidence requests, and later repayment obligations.',
    sourceUrl: 'https://www.helb.co.ke/',
    answer: 'HELB publishes the current loan, scholarship, and repayment products and their application channels. Students should select the product matching their institution and cycle, submit truthful household information, and keep the award and repayment notices.',
    steps: ['Read the current product announcement and confirm institution and applicant eligibility.', 'Create a personal HELB account and complete every required field.', 'Upload or submit evidence in the format and window stated by HELB.', 'Monitor the portal and keep the award, disbursement, and repayment communication after graduation.'],
    documents: ['National identity and contact details.', 'Admission or registration evidence.', 'Parent, guardian, or household evidence requested by the product.', 'Application reference, award notice, and later employment details.'],
    mistakes: ['Using a broker who promises approval.', 'Entering household data that cannot be supported.', 'Ignoring repayment communication because study has ended.'],
    caveat: 'Products, limits, dates, and repayment terms are announced for particular cohorts. Read the live HELB notice and ask HELB about a disputed status.',
  },
  {
    title: 'France Carte Vitale and Ameli: A New Resident’s Health-Account Setup',
    slug: 'france-ameli-carte-vitale-new-resident-guide',
    category: 'France Digital Services',
    focusKeyword: 'France Ameli account Carte Vitale',
    excerpt: 'Set up health-insurance administration safely and distinguish social-security registration from residence status.',
    sourceUrl: 'https://www.ameli.fr/assure/english-pages',
    answer: 'After affiliation to French health insurance, eligible users may use ameli services and request or update a Carte Vitale according to Assurance Maladie instructions. An ameli account is not proof of immigration status and activation depends on the person’s file.',
    steps: ['Wait for or check the affiliation number and instructions from CPAM.', 'Create an ameli account only through ameli.fr and verify the postal address.', 'Request or update the Carte Vitale when the account allows it.', 'Use secure messaging for a missing document and keep correspondence with CPAM.'],
    documents: ['Identity and residence evidence requested for affiliation.', 'Social-security number or temporary number.', 'Bank details in the format CPAM requests.', 'Photo and signature evidence for the card when required.'],
    mistakes: ['Sending bank details to a phishing email.', 'Assuming a Carte Vitale replaces private travel insurance or a residence permit.', 'Creating duplicate accounts when a file is still being processed.'],
    caveat: 'Eligibility, processing, reimbursement, and account features depend on the person’s affiliation and can change. CPAM and ameli are the authoritative channels.',
  },
  {
    title: 'International Driving Permit: Check the Issuing Country Before Travel',
    slug: 'international-driving-permit-official-checklist',
    category: 'International Procedures',
    focusKeyword: 'international driving permit application',
    excerpt: 'A country-neutral checklist for obtaining an International Driving Permit from the authority that issued your licence.',
    sourceUrl: 'https://www.gov.uk/driving-abroad/get-an-idp',
    answer: 'An International Driving Permit is generally a translation or accompanying document tied to a valid domestic driving licence; it is not a standalone licence. The issuing country’s motoring authority and the destination’s rules determine whether and which convention document is accepted.',
    steps: ['Check the destination authority or embassy for the convention and permit it accepts.', 'Identify the authorised issuer in the country that issued your domestic licence.', 'Apply with the valid licence, identity evidence, photo, and fee required by that issuer.', 'Carry both documents and check local insurance, rental, and residence rules before driving.'],
    documents: ['Valid domestic driving licence.', 'Passport or identity evidence and compliant photograph.', 'Application and payment confirmation from the authorised issuer.', 'Rental, insurance, and translation evidence if the destination requests it.'],
    mistakes: ['Buying a permit from an unrelated travel website.', 'Carrying the permit without the underlying licence.', 'Assuming a permit changes age, vehicle-class, or local residence rules.'],
    caveat: 'Issuers, conventions, fees, validity periods, and destination recognition differ. Confirm with the destination’s official transport authority before travel.',
  },
];

export const researchedContentEuropeAfrica: ExpansionPost[] = researchSeedsEuropeAfrica.map(p => ({
  title: p.title,
  slug: p.slug,
  category: p.category,
  focusKeyword: p.focusKeyword,
  excerpt: p.excerpt,
  sourceUrl: p.sourceUrl,
  body: body(p),
}));
